name       : engrampa
version    : 1.19.2
release    : 1009
source     :
    - https://pub.mate-desktop.org/releases/1.19/engrampa-1.19.2.tar.xz : 35f323d27b348d9b3af2c2b73f6f26cd137367fe80d02c4de61eb4342fbda4e4
license    : GPL-2.0
component  : desktop.mate
summary    : Archive manager for the MATE Desktop
description: |
    Archive manager for the MATE Desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(sm)
    - itstool
setup      : |
    %configure --with-gtk=3.0 --enable-magic --disable-static
build      : |
    %make
install    : |
    %make_install
