name       : mate-power-manager
version    : 1.19.0
release    : 10010
source     :
    - https://pub.mate-desktop.org/releases/1.19/mate-power-manager-1.19.0.tar.xz : e8ed295576f1ce9ebf5b9cf6111f8a6425a7718ef6f135a6d892c2b20d0e9f56
license    : GPL-2.0
component  : desktop.mate
summary    : Power Managment for the MATE Desktop
description: |
    Power Management for the MATE Desktop
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnotify)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(unique-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(x11)
    - pkgconfig(xrender)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
