name       : mate-settings-daemon
version    : 1.19.2
release    : 10016
source     :
    - https://pub.mate-desktop.org/releases/1.19/mate-settings-daemon-1.19.2.tar.xz : 5db480e73f7589575991ffa5d44accd4a7ea60d3cec544041271febf6a128ec1
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.mate
summary    : MATE Settings Daemon
description: |
    Settings Daemon for the MATE Desktop
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(fontconfig)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmatekbdui)
    - pkgconfig(libmatemixer)
    - pkgconfig(libmatekbd)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(libxklavier)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(nss)
    - pkgconfig(sm)
rundeps    :
    - xmodmap
    - xrdb
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directories.patch
    %reconfigure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
