name       : mate-system-monitor
version    : 1.19.1
release    : 1008
source     :
    - https://pub.mate-desktop.org/releases/1.19/mate-system-monitor-1.19.1.tar.xz : c64237d0960a3e30897cb17c57a1417b5966eb82247e6e3348bc714703f8d21f
license    : GPL-2.0
component  : desktop.mate
summary    : MATE System Monitor
description: |
    MATE System Monitor
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsystemd)
    - pkgconfig(libwnck-3.0)
    - itstool
setup      : |
    %configure --enable-systemd
build      : |
    %make
install    : |
    %make_install
